# Generated by Django 6.0.4 on 2026-10-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencehistory',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
