# Generated by Django 6.0.4 on 2026-05-31 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0004_occurrence_anon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
