# Generated by Django 6.0.4 on 2026-06-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0005_alter_occurrence_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
    ]
