# Generated by Django 6.0.4 on 2026-06-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0008_alter_occurrence_latitude_alter_occurrence_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=100, null=True),
        ),
    ]
